# Generated by Django 4.1.5 on 2023-01-04 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.TextField()),
                ('created', models.DateTimeField(verbose_name='channel crée le')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('biography', models.TextField()),
                ('avatar', models.TextField()),
                ('join_date', models.DateTimeField(verbose_name='inscrit depuis le')),
                ('last_active', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('published', models.DateTimeField(verbose_name='message publié le')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tchat.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tchat.user')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('last_read', models.DateTimeField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tchat.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tchat.user')),
            ],
        ),
    ]
